export const INCREASE_AMOUNT = "INCREASE_AMOUNT";
export const DECREASE_AMOUNT = "DECREASE_AMOUNT";
export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const ADD = "ADD";
export const REMOVE = "REMOVE";

// const actions = {
//   INCREASE_AMOUNT: INCREASE_AMOUNT,
//   DECREASE_AMOUNT: DECREASE_AMOUNT,
//   GET_PRODUCTS: GET_PRODUCTS,
//   GET_PRODUCTS_SUCCESS: GET_PRODUCTS_SUCCESS,
//   ADD: ADD,
//   REMOVE: REMOVE,
// };

export type ActionTypeT =
  | "INCREASE_AMOUNT"
  | "DECREASE_AMOUNT"
  | "GET_PRODUCTS"
  | "GET_PRODUCTS_SUCCESS"
  | "ADD"
  | "REMOVE";

// export default actions;
